### ISSUE TITLE
Ignore under layer

### ISSUE THREAD

**Issue by rodi01** [ozzik/Slicer#1] opened 2016-09-28 19:49 UTC
<img width="912" alt="screen shot 2016-09-28 at 12 47 35 pm" src="https://cloud.githubusercontent.com/assets/52461/18929568/e090ad7c-8579-11e6-80ea-5a5c01cb3673.png">

If I export Group A, it also exports the yellow color of Group B

Thanks, 
Rodrigo

**Comment by ozzik** [comment] 2016-10-08 18:00
Hey Rodrigo, that's kinda by design since the plugin aims to replace exporting multiple slices from a dedicated "slices" artboard (hence it literally creates slices instead of exporting layers).

That being said, will do my best to support this case and update you 👷

**Comment by ozzik** [comment] 2016-10-09 16:56
Turned out to be simpler to implement than expected :)
Just released 0.4.0, plz try it and lmk how it goes!

(https://github.com/ozzik/Slicer/commit/5e90942594ae86b9ef72fcdc53881a61bb3614bf)

**Comment by ozzik** [comment] 2016-10-13 16:58
Closing for now :)

**Closed as completed by ozzik** 2016-10-13 16:58 UTC
Labels: feature request
